theme: jekyll-theme-slate
title: "Why Donald Trump Embraces Conspiracy Theories"
description: "A Deep Dive into YouTube’s Role in Amplifying Controversy and Captivating Audiences"

author:
  name: "KungFuCooking"
  email: "gyj.6.6.6.gyj@gmail.com"

defaults:
  -
    scope:
      path: "assets/images" # 静态资源路径
    values:
      layout: "default"

